spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:loadbalance://127.0.0.1:3307/db2022?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456